### ISSUE TITLE
Fails to Build on 29.0.2 branch

### ISSUE THREAD

**Issue by gardotd426** [KDERazorback/obs-studio-retroglx#2]
Hey, trying to build the 29.0.2 branch using a PKGBUILD, get the following error:

```
[ 53%] Built target libobs-opengl
In function ‘DecodeTEA’,
    inlined from ‘HandleInvoke’ at /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/obs-outputs/librtmp/rtmp.c:3151:21:
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/obs-outputs/librtmp/rtmp.c:4575:7: error: ‘*(uint32_t *)out’ may be used uninitialized [-Werror=maybe-uninitialized]
 4575 |     y = v[0];
      |     ~~^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/build.make:272: plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1666: plugins/obs-outputs/CMakeFiles/obs-outputs.dir/all] Error 2
[ 53%] Linking C shared module obs-filters.so
Installing obs-filters to OBS rundir
[ 53%] Built target obs-filters
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-source.cpp: In member function ‘void AJASource::GenerateTestPattern(NTV2VideoFormat, NTV2PixelFormat, NTV2TestPatternSelect)’:
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-source.cpp:170:36: warning: ‘virtual bool NTV2TestPatternGen::DrawTestPattern(NTV2TestPatternSelect, uint32_t, uint32_t, NTV2FrameBufferFormat, NTV2TestPatBuffer&)’ is deprecated [-Wdeprecated-declarations]
  170 |                 gen.DrawTestPattern(ps, fd.GetRasterWidth(),
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
  171 |                                     fd.GetRasterHeight(), pix_fmt,
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  172 |                                     mTestPattern);
      |                                     ~~~~~~~~~~~~~
In file included from /usr/include/ajalibraries/ajantv2/includes/ntv2publicinterface.h:11,
                 from /usr/include/ajalibraries/ajantv2/includes/ntv2vpid.h:12,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-enums.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-props.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-card-manager.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-source.cpp:1:
/usr/include/ajalibraries/ajantv2/includes/ntv2testpatterngen.h:175:25: note: declared here
  175 |                 virtual NTV2_DEPRECATED_f(bool DrawTestPattern (const NTV2TestPatternSelect inPat, const uint32_t inWdth, const uint32_t inHght, const NTV2FrameBufferFormat inPF, NTV2TestPatBuffer & outBuf));
      |                         ^~~~~~~~~~~~~~~~~
[ 54%] Linking C shared module obs-ffmpeg.so
Installing obs-ffmpeg to OBS rundir
[ 54%] Built target obs-ffmpeg
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp: In static member function ‘static void aja::Routing::StartSourceAudio(const SourceProps&, CNTV2Card*)’:
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp:150:31: warning: ‘virtual bool CNTV2Card::WriteAudioSource(ULWord, NTV2Channel)’ is deprecated [-Wdeprecated-declarations]
  150 |         card->WriteAudioSource(0, channel);
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/ajalibraries/ajantv2/includes/ntv2publicinterface.h:11,
                 from /usr/include/ajalibraries/ajantv2/includes/ntv2vpid.h:12,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-enums.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-props.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-card-manager.hpp:3,
                 from /home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp:1:
/usr/include/ajalibraries/ajantv2/includes/ntv2card.h:2482:21: note: declared here
 2482 |         AJA_VIRTUAL NTV2_DEPRECATED_f(bool WriteAudioSource (const ULWord inValue, const NTV2Channel inChannel = NTV2_CHANNEL1));       ///< @deprecated        This function is obsolete.
      |                     ^~~~~~~~~~~~~~~~~
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp:185:34: warning: ‘virtual bool CNTV2Card::ReadAudioSource(ULWord&, NTV2Channel)’ is deprecated [-Wdeprecated-declarations]
  185 |         if (card->ReadAudioSource(oldValue, channel)) {
      |             ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/usr/include/ajalibraries/ajantv2/includes/ntv2card.h:2483:21: note: declared here
 2483 |         AJA_VIRTUAL NTV2_DEPRECATED_f(bool ReadAudioSource (ULWord & outValue, const NTV2Channel inChannel = NTV2_CHANNEL1));   ///< @deprecated        This function is obsolete.
      |                     ^~~~~~~~~~~~~~~~~
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp:186:39: warning: ‘virtual bool CNTV2Card::WriteAudioSource(ULWord, NTV2Channel)’ is deprecated [-Wdeprecated-declarations]
  186 |                 card->WriteAudioSource(oldValue | magicAudioBits, channel);
      |                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/ajalibraries/ajantv2/includes/ntv2card.h:2482:21: note: declared here
 2482 |         AJA_VIRTUAL NTV2_DEPRECATED_f(bool WriteAudioSource (const ULWord inValue, const NTV2Channel inChannel = NTV2_CHANNEL1));       ///< @deprecated        This function is obsolete.
      |                     ^~~~~~~~~~~~~~~~~
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp: In static member function ‘static void aja::Routing::ConfigureOutputAudio(const OutputProps&, CNTV2Card*)’:
/home/matt/tmp/makepkg/obs-studio-git/src/obs-studio-git/plugins/aja/aja-routing.cpp:545:42: warning: ‘virtual bool CNTV2Card::SetAudioOutputMonitorSource(NTV2AudioMonitorSelect, NTV2Channel)’ is deprecated [-Wdeprecated-declarations]
  545 |         card->SetAudioOutputMonitorSource(NTV2_AudioChannel1_2, channel);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/ajalibraries/ajantv2/includes/ntv2card.h:7406:28: note: declared here
 7406 |         AJA_VIRTUAL inline NTV2_DEPRECATED_f(bool SetAudioOutputMonitorSource (const NTV2AudioMonitorSelect inChannelPair, const NTV2Channel inAudioSystem = NTV2_CHANNEL1))    {return SetAudioOutputMonitorSource(inChannelPair, NTV2AudioSystem(inAudioSystem));}    ///< @deprecated        Use the function that uses NTV2AudioChannelPair and NTV2AudioSystem params.
      |                            ^~~~~~~~~~~~~~~~~
[ 54%] Linking CXX shared module aja.so
Installing aja to OBS rundir
[ 54%] Built target aja
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

PKGBUILD has nothing weird, just using the `obs-studio-git` PKGBUILD and replacing the source with yours.
